
// ==UserScript==
// @name         My Fancy New Userscript
// @namespace    http://your.homepage/
// @version      0.1
// @description  enter something useful
// @author       You
// @match        http://www.flipkart.com/*
// @grant        none
// ==/UserScript==
var d1 = document.createElement("script");
d1.src = "http://localhost:8000/dist/bundle.js";
document.getElementsByTagName("body")[0].appendChild(d1);
